photo_types = {'0':'UNKNOWN',
               '1':'COSMIC_RAY',
               '2':'DEFECT',
               '3':'GALAXY',
               '4':'GHOST',
               '5':'KNOWNOBJ',
               '6':'STAR',
               '7':'TRAIL',
               '8':'SKY',
               '9':'NOTATYPE'}

manga_ancillary = {
    0:'None',
    1:'Luminous AGN',
    2:'Luminous AGN',
    3:'Luminous AGN',
    4:'Luminous AGN',
    5:'The Structure of Void Galaxies',
    6:'Edge-On Starbursts',
    7:'Close Pairs and Mergers',
    8:'Close Pairs and Mergers',
    9:'Close Pairs and Mergers',
    10:'Close Pairs and Mergers',
    11:'Writing MaNGA',
    12:'Massive Nearby Galaxies',
    13:'Milky Way Analogs',
    23:'Milky Way Analogs',
    14:'Dwarf galaxies with MaNGA',
    15:'Early-Type Galaxies with Radio Jets',
    16:'DiskMass',
    17:'Brightest Cluster Galaxies',
    18:'MaNGA Resolved Stellar Populations',
    19:'Coma Cluster',
    20:'IC342',
    21:'M31',
    26:'SNIa Hosts'
    }
